name: CodeQL Analysis

on: push

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CodeQL CLI
        run: |
          # Replace `12.0.2` with the version of the CodeQL CLI you want to install
          curl -L https://github.com/github/codeql-cli-binaries/releases/download/v12.0.2/codeql-linux64.zip -o codeql.zip
          unzip codeql.zip -d $HOME
          echo "export PATH=$HOME/codeql:$PATH" >> $GITHUB_ENV

      - name: Setup CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: python
          # Set the CodeQL database path to the directory containing your Python files
          # (e.g., `.` for the root directory)
          database-path: .

      - name: Run CodeQL analysis
        run: codeql analyze --no-compile python

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Set the path to the SARIF file generated by CodeQL analysis
          sarif_file: codeql-analysis.sarif
